#!/usr/bin/env node
'use strict';

let {pipeline} = require('stream')

let FeedParser = require('feedparser')
let minimist = require('minimist')

let MailStream = require('./index')

let argv = minimist(process.argv.slice(2), {
    boolean: ['rnews'],
    string: ['f']
})
pipeline(process.stdin, new FeedParser(), new MailStream(argv), process.stdout, err => {
    if (err && err.code !== 'EPIPE') {
	console.error(err)
	process.exitCode = 1
    }
})
